### ISSUE TITLE
Change color of SideBar

### ISSUE THREAD

**Issue by Guilherd74** [LaGuer/SixtySecondsCV#1]
Hello! I don't know if I didn't find it, but is there a way to change the colour of your informations on the SideBar? It is always black and I would like to change it to white, because the back of my sidebar (which in the code is "sidecolour") is black. Thank you!

**Comment by LaGuer** [comment]
Hi @Guilherd74 
Current attributes set to sidecolor=gray!50, in \documentclass
Thx
